### ISSUE TITLE
Power Calculation is 0

### ISSUE THREAD

**Issue by jjgiesey** [Milligan-Engineering/SolarSysSpecif#5]
Looks like a problem in the power calculation

![image](https://user-images.githubusercontent.com/35739578/75069102-7f086f00-54be-11ea-8ecf-bd747d3ef584.png)

**Comment by efforgety** [comment]
Committed new version of PM05Eval correcting the power calculation issue

**Comment by jjgiesey** [comment]
Looks like the power (watts) entry is OK. For current (Amps) P = I V.

**Comment by efforgety** [comment]
This should be correct. I have the calculation set up as ( I V )/1000 to convert to kilowatts

**Comment by jjgiesey** [comment]
Good.
