### ISSUE TITLE
PM09b Issue #1

### ISSUE THREAD

**Issue by Oakes73** [Milligan-Engineering/SolarSysSpecif#7]
Hey Erin,

As long as you follow the directions of your program, It works great, The few issues I have found have just been user input. The first issue is that all of the parts that I tried, whenever asked for an integer, if a user would happen to enter a letter or any other character it would crash the program or when entering Insolation values if entered an integer it would keep going but crash when done entering all values!

**Comment by efforgety** [comment]
Added do-while loops to check input on switch functions, and added instruction to enter numerical values only for filling arrays and integer only for variables of type int
