### ISSUE TITLE
PM09b Issue #2

### ISSUE THREAD

**Issue by Oakes73** [Milligan-Engineering/SolarSysSpecif#8]
Hey, the second issue is that when asked to enter isolation loads, it says a maximum of 10 at a time, if the user was to enter a number higher than that, the program would continue, and go up to 11 and pause and crash!
![EENG SS Test 1](https://user-images.githubusercontent.com/60352593/78400981-bb52e300-75c5-11ea-9600-510a60671f5c.PNG)

**Comment by efforgety** [comment]
Added a while function on line 68 that asks the user to reenter a number until the user enters a number in the given range.
